<?php
// $Id$

/*
 * @file
 * Drupal Module: grammateus-reader
 * Adds custom code specific to this Drupal 6 site.
 */

// keep the module name consistent throughout
global $moduleName;
$moduleName = "grammateus-reader";

//call help hook to create a help entry for the module
function grammateus-reader_help($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#".$moduleName:
      $output = '<p>'.t("Provides two blocks, one of which displays provides interactive display of text from an xml file, the other of which provides navigation controls for the display block.") .'</p>';
      break;
  }
  return $output;
} // function grammateus-reader_help

//call permissions hook to set permission categories for the module on the permissions page
function grammateus-reader_perm() {
  return array('access grammateus-reader content', 'administer grammateus-reader');
} // function grammateus-reader_perm()

// call menu hook to create an administration menu to create content for module
function grammateus-reader_menu() {
global $moduleName;
$items = array();
$items['admin/settings/'.$moduleName] = array(
'title' => ucfirst($moduleName),
'description' => 'Set '.$moduleName.' code',
'page callback' => 'drupal_get_form',
'page arguments' => array($moduleName.'_admin'),
'access arguments' => array('access administration pages'),
'type' => MENU_NORMAL_ITEM,
);
return $items;
}

// call admin hook to let you administrate the content of this hello block
function grammateus-reader_admin() {
global $moduleName;
$form = array();
$form[$moduleName.'_show_title'] = array(
'#type' => 'checkbox',
'#title' => t('Show title'),
'#default_value' => variable_get($moduleName.'_show_title', '1'),
'#required' => TRUE,
);
$form[$moduleName.'_number'] = array(
'#type' => 'textfield',
'#title' => t('How many blocks'),
'#default_value' => variable_get($moduleName.'_number', '1'),
'#maxlength' => 3,
'#required' => TRUE,
);
$n = (int)variable_get($moduleName.'_number',1);
for( $i=1;$i<$n+1;$i++ ) {
($i<2) ? $setreq = TRUE : $setreq = FALSE;
$form[$moduleName.'_'.$i] = array(

'#type' => 'textarea',
'#title' => t(ucfirst($moduleName).' Block '.($i)),
'#default_value' => variable_get($moduleName.'_'.$i, ''),
'#maxlength' => 800,
'#required' => $setreq,
);
}
return system_settings_form($form);
}

// call block hook and show in Drupal block the you assign
function grammateus-reader_block($op = 'list', $delta = array(), $edit = array()) {

global $moduleName;

//include custom css stylesheet for module
drupal_add_css(drupal_get_path('module', $moduleName) .'/'.$moduleName.'.css');

//include custom javascript files for module, located in module directory
drupal_add_js(drupal_get_path('module', $moduleName) .'/'.$moduleName.'.js');
drupal_add_js(drupal_get_path('module', $moduleName) .'/js/jquery.xmldom-1.0.min.js');
drupal_add_js(drupal_get_path('module', $moduleName) .'/js/jQueryString/jQueryString-2.0.2-Min.js');
drupal_add_js(drupal_get_path('module', $moduleName) .'/js/jquery.mousewheel.3.0.2/jquery.mousewheel.3.0.2/jquery.mousewheel.min.js');
drupal_add_js(drupal_get_path('module', $moduleName) .'/js/jquery.cookie.js');
drupal_add_js(drupal_get_path('module', $moduleName) .'/js/jquery.event.drag-2.0.min.js');
drupal_add_js(drupal_get_path('module', $moduleName) .'/js/jquery.ba-bbq.min.js');

//include jquery ui scripts via the jquery_ui utility module
//jquery_ui_add(array('ui.resizable', 'ui.draggable', 'ui.droppable'));
switch($op)
{
  case "list":
    // Generate listing of blocks from this module, for the admin/block page
    $blocks = array();
    $blocks[0]["info"] = t('Grammateus Reader Text Block');
    $blocks[1]["info"] = t('Grammateus Reader Controls Block');
    return $blocks;
    break;

// block content begins
  case "view":
    switch($delta){
      case 0:

$structure = t('<div id="versionContainer">

  <div id="v1" class="versionColumn">

    <div class="versionHeader">
      <form><label>Version</label> <select class="versionSelector"></select></form>
      <a class="versionCloserLink" href="#" title="Click to close this language version"></a>
    </div>

    <div id="c1" class="containerCell">
      <div id="tt1-1" class="textType">

        <div id="n1-1" class="msNavRow">
          <form><label>Text type</label> <select class="msSelector"></select></form>
          <a href="#" class="msCloserLink" title="Click to close this text type"></a>
        </div>

        <div id="dd1-1" class="msDisplayRow">
          <img src="sites/all/modules/bookDisplay/images/ajax-loader.gif" />
          <div class="textScroller" id="ts1-1"></div>
        </div>

        <div id="h1-1" class="textHandle"></div>
      </div>

      <div class="textAdder">
        <a class="textAdderLink" href="#" title="Click to add another text type"></a>
      </div>

    </div>

    <div id="a1" class="apparatusCell">
      <div id="ah1" class="apparatusHandle"></div>

      <table class="apparatusTable">
        <tr class="apparatusHeaderRow">
          <th class="apparatusHeader"><span>Text Types</span></th>
          <th class="apparatusHeader"><span>Reading</span> <a class="apparatusToggle" href="#" title="Click to close the critical apparatus">X</a></th>
        </tr>
      </table>

      <span class="apparatusLabel">Click on a section of blue text to view available textual variants for those words.</span>

    </div>

  </div>

  <div class="versionAdder">
    <a class="versionAdderLink" href="" title="Click to add another language version"></a>
  </div>

</div>');
  break;

  case 1:

$structure = t('<div id="chapterNav">

<div id="settingControls">
  <a id="fontLarger" href=""><img src="/sites/all/modules/bookDisplay/images/zoom-in.png" title="Increase text size" /></a>
  <a id="fontSmaller" href=""><img src="/sites/all/modules/bookDisplay/images/zoom-out.png" title="Decrease text size" /></a>
  <a id="printer-friendly" class="printer-friendly" href=""><img src="/sites/all/modules/bookDisplay/images/print.png" title="Open printer-friendly view" /></a>
</div>

  <form id="chapterNavForm" method="post" action="">
    <label for="startRef1"></label>
    <input type="text" name="startRef1" id="startRef1" />
    <label for="endRef1">to</label>
    <input type="text" id="endRef1" name="endRef1" />
    <a id="ref1Submit" href="">Go</a>
  </form>

<div id="prev-nextLinks">
  <a id="beginLink" href="">
    <img src="/sites/all/modules/bookDisplay/images/first.png" title="Go to the beginning" />
  </a>
  <a id="prevLink" href="">
    <img src="/sites/all/modules/bookDisplay/images/previous.png" title="Go to the previous section" />
  </a>
  <a id="nextLink" href="">
    <img src="/sites/all/modules/bookDisplay/images/next.png" title="Go to the next section" />
  </a>
  <a id="endLink" href="">
    <img src="/sites/all/modules/bookDisplay/images/end.png" title="Go to the end" />
  </a>
</div>

</div>');
    break;
    }

  $blocks['content'] = $structure;

return $blocks;

}//else if $op == view

}// function grammateus-reader_block
